version: '3.9'
services:
  express:
    image: ai-google-calender-image
    container_name: ai-google-calender-container
    build:
      context: .
      dockerfile: ./container/nodejs/Dockerfile
    volumes:
      - ./express:/app
    ports:
      - "8080:8080"
    command: yarn start
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ".env"
