version: '3.9'
services:
  express:
    image: ai-google-calender-prod-image
    container_name: ai-google-calender-prod-container
    build:
      context: .
      dockerfile: ./container/nodejs/Dockerfile.Prod
    ports:
      - "8080:8080"
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ".env"
